### ISSUE TITLE
HTML is not properly displayed in ApiType descriptions

### ISSUE THREAD

**Issue by ST-DDT** [joffrey-bion/livedoc#115]
**Describe the bug**

If there is HTML in the javadoc of a property it will be displayed as plain text and not handled as HTML.
HTML in javadocs of types works as expected.

**Expected behavior**

HTML javadocs works for both class level and field level javadoc.

**Screenshots**

![nothtml](https://user-images.githubusercontent.com/1579362/40053459-9ca88d4a-5841-11e8-911b-f7fc5b10df45.png)

**Environment/Context**

* Livedoc-Spring + UI 4.5.2

Small extract from the generated json
````json
{
"description": "The full amount .... \n ...\n entry. Precision is limited to one decimal digit. It will use the\n <code>RoundingMode#HALF_UP</code>."
}
````
And here the source file.
````java
/**
 * The full amount ...
 * ...
 * entry. Precision is limited to one decimal digit. It will use the
 * {@link RoundingMode#HALF_UP}.
 */
public Numeric amount;
````

**Comment by joffrey-bion** [comment]
Thanks for opening this, I had noticed it last week and fixed it in commit eff70c605b65c99aedc22bcca1f457309614f5f3.
It will be part of the next release.
