### ISSUE TITLE
@RequestMapping using regex not working in UI

### ISSUE THREAD

**Issue by Shinigami92** [joffrey-bion/livedoc#122]
**Describe the bug**
If you have a `@Controller`/`@RestController` with a method that contains a `@RequestMapping` that uses Regex, you can not unfold this method in the UI

example: `@RequestMapping("/{id:[0-9]+}")`

**Expected behavior**
Expandable UI element for the method

**Screenshots**
If you can wait until tomorrow, I can take a screenshot at work

**Environment/Context**
- Livedoc version: v5.0.0
- Livedoc flavour: Spring MVC
- Spring version: 5.0.6.RELEASE
- Java: 9

**Comment by Shinigami92** [comment]
Two errors are shown in the DEV-Console when clicking on the element

![livedoc - google chrome_078](https://user-images.githubusercontent.com/7195563/43764760-9eb36a9a-9a2e-11e8-9f5b-b0ce7b7393dc.png)

The jsondoc part looks like this:
```json
{
	"jsondocErrors": [],
	"jsondocWarnings": [],
	"jsondocHints": [
		"Add description to ApiOperation",
		"Add description to ApiPathParam"
	],
	"name": "update",
	"summary": null,
	"description": null,
	"paths": [
		"***/update/{id:[0-9]+}"
	],
	"verbs": [
		"PUT"
	],
	"pathParameters": [{
		"jsondocErrors": [],
		"jsondocWarnings": [],
		"jsondocHints": [],
		"type": {
			"typeElements": [{
				"text": "long",
				"livedocId": null
			}],
			"composingTypes": [
				"long"
			],
			"oneLineText": "long"
		},
		"name": "id",
		"description": null,
		"required": "true",
		"allowedValues": [],
		"format": null,
		"defaultValue": null
	}],
	"queryParameters": [],
	"headers": [],
	"requestBody": {
		"type": {
			"typeElements": [{
					"text": "Map",
					"livedocId": null
				},
				{
					"text": "<",
					"livedocId": null
				},
				{
					"text": "String",
					"livedocId": null
				},
				{
					"text": ", ",
					"livedocId": null
				},
				{
					"text": "Object",
					"livedocId": null
				},
				{
					"text": ">",
					"livedocId": null
				}
			],
			"composingTypes": [
				"java.util.Map",
				"java.lang.String",
				"java.lang.Object"
			],
			"oneLineText": "Map<String, Object>"
		},
		"template": {}
	},
	"responseBodyType": {
		"name": "DTO",
		"oneLineText": "DTO",
		"typeElements": [{
			"text": "DTO",
			"livedocId": null
		}],
		"composingTypes": []
	},
	"consumes": [
		"application/json"
	],
	"produces": [
		"application/json"
	],
	"responseStatusCode": "200 - OK",
	"apiErrors": [],
	"auth": null,
	"supportedVersions": null,
	"stage": null,
	"livedocId": "put-***-update-id%3A%5B0-9%5D%2B"
}
```

_i have masked some parts with ***_

**Comment by joffrey-bion** [comment]
Thanks again for opening issues, it really helps me improve Livedoc.

Regarding the part hidden with stars, is it properly URL-encoded? It is just plain ascii, isn't it?

**Comment by joffrey-bion** [comment]
I managed to reproduce using the same regex as you.
It looks like the square brackets are the culprits. WIthout them, even with a regex, it seems to work.
Strangely enough the brackets *are* encoded properly in the JSON output of livedoc, however they seem to be decoded when storing the ID on client side.

I'm at work right now, but I'll try to get this fixed tonight and release a patch tomorrow.

**Comment by joffrey-bion** [comment]
The problem seems due to the fact that react-router decodes the path I gave it, despite the fact that I took care of properly URL-encode this stuff to avoid this kind of problems!

This [router issue](https://github.com/ReactTraining/react-router/issues/5816) comes from this [history issue](https://github.com/ReactTraining/history/issues/505)

I'll look for a simple solution to work around that, but I believe it is annoying and unexpected from the router to do this sort things.
