### ISSUE TITLE
Create a maintainable UI

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/livedoc#28]
The current UI code is not quite maintainable, and should be rewritten in some recent Javascript UI framework like React.

**Comment by ST-DDT** [comment]
You could also use vue (or Angular(JS)).

**Comment by joffrey-bion** [comment]
Indeed, but I have started something in React already, because I wanted some more practice with it :)

@mebubo was thinking about a purescript implementation, using [pux](https://github.com/alexmingoia/purescript-pux) or [halogen](https://github.com/slamdata/purescript-halogen).
