### ISSUE TITLE
Move annotations to own jar/lib

### ISSUE THREAD

**Issue by ST-DDT** [joffrey-bion/livedoc#33]
It would be nice if you could move the annotation to their own jar/lib.

Because we also have a separate jar for the dto classes, it is bothersome to add the core package as dependency and exclude all of its dependencies.

Annotations are optional thus it is not necessary to be present on the classpath during runtime.

![deps dot](https://user-images.githubusercontent.com/1579362/30855469-73830cde-a2b5-11e7-8769-ef7b0db454e1.png)

**Comment by joffrey-bion** [comment]
Thanks for the proposition, it looks like some projects could benefit from it indeed.
I'll probably perform this separation tonight or tomorrow.
