### ISSUE TITLE
ObjectMapper custom configuration is ignored by Livedoc

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/livedoc#43]
Livedoc currently recreates an `ObjectMapper` object instead of reading Spring's actual `ObjectMapper` instance used for Jackson HTTP messages conversion.

One consequence of it is https://github.com/joffrey-bion/livedoc/issues/42

**Comment by ST-DDT** [comment]
Please keep in mind that there is no ObjectMapper Spring Bean that will be used by all HttpMessageConverters. Instead each converter will contain its own instance with its own configuration.

**Comment by joffrey-bion** [comment]
Yes, I'm aware of this. That's why I used the one from the Jackson converter instead of relying on the bean.
That being said, in Spring Boot, I read that you may create you own ObjectMapper bean, and it would be used by spring for the converters. I haven't confirmed that myself though.
