### ISSUE TITLE
Add default value for java.util.Date in templates

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/livedoc#45]
Dates have a special treatment in Jackson, therefore it does not make sense to create `LinkedHashMap` with their properties, they should be put in templates as actual `Date` objects.

**Comment by ST-DDT** [comment]
This also affects `java.time.*`.

**Comment by joffrey-bion** [comment]
I  believe this list covers all use cases:
- `java.util.Date`
- `java.time.TemporalAmount`
- `java.time.TemporalAccessor`

Do you see anything that is not covered by these 3 types?

**Comment by ST-DDT** [comment]
I guess that list is complete (or at least easy to supplement later)
