### ISSUE TITLE
Add quick-start documentation in the README

### ISSUE THREAD

**Issue by joffrey-bion** [joffrey-bion/livedoc#48]
Even without a comprehensive and detailed documentation about the ins and outs of Livedoc, we should at least provide a quickstart guide for each way of using Livedoc:
- using `livedoc-core` and creating a `LivedocReader` (and potentially a controller or some sort of access to the JSON documentation)
- using `livedoc-springmvc` and creating a basic controller
- using `livedoc-springboot` and `application.properties`

Also, of course, mention the UI webjar and how to use it.

**Comment by ST-DDT** [comment]
Also would it be possible for you to host the ui somewhere so that it is easier to look at? (and link it in the readme)

Maybe one some of these mysterious github.io pages?

**Comment by joffrey-bion** [comment]
@ST-DDT Targeting someone's own doc from an externally-hosted UI was so far not possible because of https://github.com/joffrey-bion/livedoc/issues/35.

Do you mean a UI to access some sort of showcase doc like in the original JsonDoc project?
That would indeed be possible, and it is planned, it was just not my priority right now, as I'm trying to have a clean and running lib before writing a showcase :) I'll open a separate issue for that.

For now, to have a glance at the UI, you may add the webjar to your dependencies and target `/livedoc-ui.html` on your own server.
