### ISSUE TITLE
Livedoc-UI forgets the url if an error occurs during loading

### ISSUE THREAD

**Issue by ST-DDT** [joffrey-bion/livedoc#80]
If I use livedoc-ui 4.2.0 and press the `Get Doc` button and I have a typo in the URL (or an error occurs), 
it will reset the input back to its default `http://localhost:8080/jsondoc`. 

It would be nice if the passed URL is preserved so you can check it for errors and fix it.

**Comment by joffrey-bion** [comment]
Good point, this is indeed annoying and should be fixed.
One way to work around this is to provide the json doc URL directly as a query parameter:

    http://your.livedoc.host/livedoc/index.html?url=http://your.app.host/jsondoc
