### ISSUE TITLE
Add URL parameter to automatically insert or load documentation URL

### ISSUE THREAD

**Issue by ST-DDT** [joffrey-bion/livedoc#81]
Sometimes you don't have the docs on the same server your application runs or at least the URL is not localhost for a co-worker of me. Thus it would be nice if it would be possible to prepare an URL that will automatically load (or suggest) the given URL.

Something like 
http://livedoc.example.com/#/fetch?url=http://10.0.0.1/myApp/jsondoc

If there is such an option already, I wasn't able to find it in the documentation.

**Comment by joffrey-bion** [comment]
You just need to provide the query param before the hash part:

    http://livedoc.example.com?url=http://10.0.0.1/myApp/jsondoc#/fetch

You may as well forget about the hash part altogether:

    http://livedoc.example.com?url=http://10.0.0.1/myApp/jsondoc

This parameter is documented in the page about Livedoc UI:
https://joffrey-bion.github.io/livedoc/livedoc-ui
