### ISSUE TITLE
Make ApiGlobalPage annotation repeatable.

### ISSUE THREAD

**Issue by ST-DDT** [joffrey-bion/livedoc#95]
It would be nice if [ApiGlobalPage](https://github.com/joffrey-bion/livedoc/blob/master/livedoc-annotations/src/main/java/org/hildan/livedoc/core/annotations/global/ApiGlobalPage.java#L6) would be `@Repeatable` so you don't have to use the additional wrapper for it.

https://docs.oracle.com/javase/tutorial/java/annotations/repeating.html

**Comment by joffrey-bion** [comment]
Didn't know about this feature at all! Good idea :)
